#!/usr/bin/env bash
# evaluate-session SessionEnd launcher — generated by install-hook.sh.
#
# Exists so settings.json holds one stable path. Pointing settings straight at
# the skill bakes in a location that moves: a plugin copy lives under a
# version-numbered directory and is replaced on every update, and a working
# checkout can be renamed or sit somewhere else on another machine. A hook whose
# path has gone stale fails silently, which is the worst way for this to break.
#
# Resolution order: an explicit override, then the newest installed plugin copy,
# then the checkout this was installed from.
set -uo pipefail

candidates=()

[ -n "${EVALUATE_SESSION_SKILL:-}" ] && candidates+=("$EVALUATE_SESSION_SKILL")

# Newest version first. Paths share a prefix, so a version sort orders them.
while IFS= read -r d; do
  [ -n "$d" ] && candidates+=("$d")
done < <(find "$HOME/.claude/plugins/cache" -maxdepth 4 -type d \
           -path '*/skills/evaluate-session' 2>/dev/null | sort -V -r)

candidates+=("@FALLBACK@")

for c in "${candidates[@]}"; do
  if [ -x "$c/scripts/hook.sh" ]; then
    exec "$c/scripts/hook.sh"
  fi
done

# Nothing resolved. Exit cleanly: a session ending is not the moment to complain.
exit 0
